openapi: 3.0.3
info:
  title: Phrase Strings API Reference Accounts Search API
  version: 2.0.0
  description: Phrase Strings is a translation management platform for software projects. You can collaborate on language file translation with your team or order translations through our platform. The API allows you to import locale files, download locale files, tag keys or interact in other ways with the localization data stored in Phrase Strings for your account.
  contact:
    name: Phrase Support
    url: https://developers.phrase.com/api/
    email: support@phrase.com
  x-logo:
    url: https://developers.phrase.com/images/phrase-logo.svg
    backgroundColor: '#03eab3'
    altText: Phrase Strings
  termsOfService: https://phrase.com/terms/
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
servers:
- url: https://api.phrase.com/v2
  description: EU production server
- url: https://api.us.app.phrase.com/v2
  description: US production server
security:
- Token: []
- Basic: []
tags:
- name: Search
paths:
  /accounts/{account_id}/search:
    post:
      summary: Search across projects
      description: 'Search for keys and translations in all account projects


        *Note: Search is limited to 10000 results and may not include recently updated data depending on the project sizes.*

        '
      operationId: search/in_account
      tags:
      - Search
      parameters:
      - $ref: '#/components/parameters/X-PhraseApp-OTP'
      - $ref: '#/components/parameters/account_id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_search_result'
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-Rate-Limit-Reset'
            Pagination:
              $ref: '#/components/headers/Pagination'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
      x-code-samples:
      - lang: Curl
        source: "curl \"https://api.phrase.com/v2/accounts/:account_id/search\" \\\n  -u USERNAME_OR_ACCESS_TOKEN \\\n  -X POST \\\n  -F query=keyword \\\n  -F locale_code=localecode \\\n  -F page=1 \\\n  -F per_page=25 \\"
      - lang: CLI v2
        source: 'phrase search in_account \

          --account_id <account_id> \

          --data ''{"q":"keyword","locale_code": "de","page": 1,"per_page": 25}'' \

          --access_token <token>'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: search/in_account/parameters
              properties:
                query:
                  description: Search query
                  type: string
                  example: keyword
                locale_code:
                  description: Locale code
                  type: string
                  example: de_DE
                page:
                  description: Page
                  type: integer
                  example: 1
                per_page:
                  description: Number of results per page
                  type: integer
                  example: 25
      x-cli-version: '2.5'
components:
  responses:
    '429':
      description: Rate Limiting
      headers:
        X-Rate-Limit-Limit:
          $ref: '#/components/headers/X-Rate-Limit-Limit'
        X-Rate-Limit-Remaining:
          $ref: '#/components/headers/X-Rate-Limit-Remaining'
        X-Rate-Limit-Reset:
          $ref: '#/components/headers/X-Rate-Limit-Reset'
    '404':
      description: Not Found
      headers:
        X-Rate-Limit-Limit:
          $ref: '#/components/headers/X-Rate-Limit-Limit'
        X-Rate-Limit-Remaining:
          $ref: '#/components/headers/X-Rate-Limit-Remaining'
        X-Rate-Limit-Reset:
          $ref: '#/components/headers/X-Rate-Limit-Reset'
    '400':
      description: Bad request
      headers:
        X-Rate-Limit-Limit:
          $ref: '#/components/headers/X-Rate-Limit-Limit'
        X-Rate-Limit-Remaining:
          $ref: '#/components/headers/X-Rate-Limit-Remaining'
        X-Rate-Limit-Reset:
          $ref: '#/components/headers/X-Rate-Limit-Reset'
  headers:
    X-Rate-Limit-Reset:
      description: Timestamp of end of current time period as UNIX timestamp, see [Rate Limiting](/en/api/strings/pagination#rate-limiting)
      schema:
        type: integer
    X-Rate-Limit-Limit:
      description: The number of allowed requests in the current period
      schema:
        type: integer
    X-Rate-Limit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        type: integer
    Pagination:
      description: Pagination details for navigating through a collection of resources, provided in JSON format.
      schema:
        type: object
        properties:
          total_count:
            description: Total count of items in the collection.
            type: integer
            example: 10
          total_pages_count:
            description: Total number of pages available for the collection.
            type: integer
            example: 2
          current_page:
            description: The current page number.
            type: integer
            example: 1
          current_per_page:
            description: Number of items currently displayed per page.
            type: integer
            example: 5
          previous_page:
            description: Page number of the previous page, if available.
            type: integer
          next_page:
            description: Page number of the next page, if available.
            type: integer
            example: 2
  parameters:
    X-PhraseApp-OTP:
      in: header
      name: X-PhraseApp-OTP
      description: Two-Factor-Authentication token (optional)
      required: false
      allowEmptyValue: false
      schema:
        type: string
    account_id:
      in: path
      name: account_id
      description: Account ID
      required: true
      schema:
        type: string
  schemas:
    project:
      type: object
      title: project
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        main_format:
          type: string
        project_image_url:
          type: string
        media:
          type: string
        account:
          $ref: '#/components/schemas/account'
        space:
          $ref: '#/components/schemas/space_short'
        point_of_contact:
          $ref: '#/components/schemas/user_preview'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      example:
        id: abcd1234cdef1234abcd1234cdef1234
        name: My Android Project
        slug: android_project
        main_format: xml
        project_image_url: http://assets.example.com/project.png
        account: account
        space: space
        created_at: '2015-01-28T09:52:53Z'
        updated_at: '2015-01-28T09:52:53Z'
    translation:
      type: object
      title: translation
      properties:
        id:
          type: string
        content:
          type: string
          x-json-tag: json:"content"
        unverified:
          type: boolean
        excluded:
          type: boolean
        plural_suffix:
          type: string
        key:
          $ref: '#/components/schemas/key_preview'
        locale:
          $ref: '#/components/schemas/locale_preview'
        placeholders:
          type: array
          items:
            type: string
        state:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        linked_translation:
          $ref: '#/components/schemas/translation_parent'
      example:
        id: abcd1234cdef1234abcd1234cdef1234
        content: My translation
        unverified: false
        excluded: false
        plural_suffix: ''
        key:
          id: abcd1234cdef1234abcd1234cdef1234
          name: home.index.headline
          plural: false
          use_ordinal_rules: false
        locale:
          id: abcd1234cdef1234abcd1234cdef1234
          name: de
          code: de-DE
        placeholders:
        - '%{count}'
        state: translated
        created_at: '2015-01-28T09:52:53Z'
        updated_at: '2015-01-28T09:52:53Z'
    space_short:
      type: object
      title: space
      properties:
        id:
          type: string
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        projects_count:
          type: integer
      example:
        id: 2e7574e8f2372906a03110c2a7cfe671
        name: My first space
        created_at: '2020-02-25T12:17:25Z'
        updated_at: '2020-03-13T14:46:57Z'
        projects_count: 2
    key_preview:
      type: object
      title: key_preview
      properties:
        id:
          type: string
        name:
          type: string
        plural:
          type: boolean
        use_ordinal_rules:
          type: boolean
      example: null
    translation_parent:
      type: object
      title: translation_parent
      properties:
        id:
          type: string
        content:
          type: string
      example:
        id: abcd1234cdef1234abcd1234cdef1234
        content: My parent translation
    account:
      type: object
      title: account
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        company:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        company_logo_url:
          type: string
      example:
        id: abcd1234
        name: Company Account
        slug: company_account
        company: My Awesome Company
        created_at: '2015-01-28T09:52:53Z'
        updated_at: '2015-01-28T09:52:53Z'
        company_logo_url: http://assets.example.com/company_logo.png
    account_search_result:
      type: object
      title: account_search_result
      properties:
        query:
          type: string
        excerpt:
          type: string
        key:
          $ref: '#/components/schemas/key_preview'
        locale:
          $ref: '#/components/schemas/locale_preview'
        project:
          $ref: '#/components/schemas/project'
        translation:
          $ref: '#/components/schemas/translation'
        other_translations:
          type: array
          items:
            $ref: '#/components/schemas/translation'
      example:
        query: keyword
        excerpt: excerpt text
        key:
          id: abcd1234cdef1234abcd1234cdef1234
          name: key.name
          plural: false
          data_type: string
          tags:
          - tag 1
          - tag 2
        locale:
          id: abcd1234cdef1234abcd1234cdef1234
          name: German
          code: de_DE
        project:
          id: abcd1234cdef1234abcd1234cdef1234
          name: project name
          slug: project-slug
          main_format: ''
          project_image_url: ''
          created_at: '2021-05-04T14:16:26Z'
          updated_at: '2021-06-14T14:26:09Z'
          account:
            id: abcd1234cdef1234abcd1234cdef1234
            name: account name
            slug: account-slug
            company: company name
            created_at: '2021-04-27T14:27:25Z'
            updated_at: '2021-06-14T14:35:15Z'
            company_logo_url: ''
          space:
            id: abcd1234cdef1234abcd1234cdef1234
            name: space name
            slug: space-slug
            created_at: '2015-01-28T09:52:53Z'
            updated_at: '2015-01-28T09:52:53Z'
            projects_count: 1
        translation:
          id: abcd1234cdef1234abcd1234cdef1234
          content: some content
          unverified: true
          excluded: false
          plural_suffix: ''
          key:
            id: abcd1234cdef1234abcd1234cdef1234
            name: key.name
            plural: false
            data_type: string
            tags:
            - tag 1
            - tag 2
          created_at: '2021-05-04T14:17:04Z'
          updated_at: '2021-05-04T14:17:04Z'
          placeholders: []
          state: translated
          locale:
            id: abcd1234cdef1234abcd1234cdef1234
            name: German
            code: de_DE
        other_translations:
        - id: abcd1234cdef1234abcd1234cdef1234
          content: some content
          unverified: true
          excluded: false
          plural_suffix: ''
          key:
            id: abcd1234cdef1234abcd1234cdef1234
            name: key.name
            plural: false
            data_type: string
            tags:
            - tag 1
            - tag 2
          created_at: '2021-05-04T14:17:04Z'
          updated_at: '2021-05-04T14:17:04Z'
          placeholders: []
          state": translated
          locale:
            id: abcd1234cdef1234abcd1234cdef1234
            name: English
            code: en_EN
    user_preview:
      type: object
      title: user_preview
      properties:
        id:
          type: string
        username:
          type: string
        name:
          type: string
        gravatar_uid:
          type: string
      example:
        id: abcd1234cdef1234abcd1234cdef1234
        username: johndoe
        name: John Doe
        gravatar_uid: 205e460b479e2e5b48aec07710c08d50
    locale_preview:
      type: object
      title: locale_preview
      properties:
        id:
          type: string
        name:
          type: string
        code:
          type: string
      example:
        id: abcd1234cdef1234abcd1234cdef1234
        name: English
        code: en-GB
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your token in the format `token TOKEN`
    Basic:
      type: http
      scheme: basic
x-tagGroups:
- name: Core Resources
  tags:
  - Projects
  - Locales
  - Keys
  - Translations
  - Uploads
  - Tags
  - Custom Metadata Properties
  - Blacklisted Keys
  - Versions / History
- name: Workflows
  tags:
  - Spaces
  - Jobs
  - Job Comments
  - Job Locales
  - Job Templates
  - Job Template Locales
  - Organization Job Templates
  - Organization Job Template Locales
  - Comments
  - Comment Reactions
  - Comment Replies
  - Branches
- name: Quality
  tags:
  - Glossaries
  - Glossary Terms
  - Glossary Term Translations
- name: Integrations
  tags:
  - Webhooks
  - Distributions
  - Releases
  - Release Triggers
- name: Ordering
  tags:
  - Orders
  - Style guides
- name: User management
  tags:
  - Authorizations
  - Users
  - Accounts
  - Members
  - Invitations
- name: Screenshots
  tags:
  - Screenshots
  - Screenshot Markers
- name: Misc
  tags:
  - Formats
- name: Figma Attachments
  tags:
  - Figma attachments
  - Key's Figma attachments
